config/routes.rb
Rails.application.routes.draw do







  devise_for :users
  root to: "static_pages#home"
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resource :account, only: [:show]
  post 'tokens' => "tokens#create"


  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'user/all' => 'users#index'
  get "notes" => 'static_pages#notes'
  get "crisis_updates" => 'crisis_updates#crisis_updates'
  get "public_resolutions" => 'resolutions#public_resolutions'
  get "private_resolutions" => 'resolutions#private_resolutions'
  get "documents" => 'static_pages#documents'
  get 'static_pages/download' => 'static_pages#download'
  get "resolution_management" => 'resolutions#resolution_management'
  get "resolution_requests" => 'resolution_requests#create'
  get "resolution_signings_create" => 'resolution_signings#create'
  delete 'resolution_signings_destroy' => 'resolution_signings#destroy'
  delete 'resolution_signings' => 'resolution_signings#destroy'
  delete 'directives_tags' => 'directives_tags#destroy'
  delete 'resolution_requests' => 'resolution_requests#destroy'
  delete 'resolution_sponsorships' => 'resolution_sponsorships#destroy'



  resources :users
  resources :crises, :controller => "users", :type => "Crisis"
  resources :delegates, :controller => "users", :type => "Delegate"

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  resources :directives
  resources :personal_directives,  :controller => "personal_directives"
  resources :resolutions, :controller => "resolutions"
  resources :crisis_updates, :controller => "crisis_updates"
  resources :notes, :controller => "notes", only: [:create, :destroy]
  resources :tags
  resources :directives_tags
  resources :resolution_sponsorships, only: [:create, :destroy]
  resources :resolution_signings, only: [:create, :destroy]
  resources :resolution_requests, only: [:create, :destroy]



















end

app/models/personal_directive.rb
class PersonalDirective < Directive
    has_many :issue_directives, :foreign_key => :directive_id
    has_many :delegates, through: :issue_directives
    
end

app/controllers/personal_directives_controller.rb
class PersonalDirectivesController < DirectivesController
  before_action :authenticate_user!
  def new
    @personal_directives = current_user.personal_directives.build
  end

  def create
      pd = current_user.personal_directives.build(content: params[:personal_directive][:content],
                                              title: params[:personal_directive][:title])
      if pd.save
        if params[:other_authors]
          params[:other_authors].each do |person|
            IssueDirective.create(user_id: person, directive_id: pd.id)
          end
        end
        flash[:success] = "Directive created!"
        current_user.issue_directives.create(directive_id: pd.id)
        redirect_to personal_directives_path
      else
        flash[:error] = "Fail"
        redirect_to request.referrer
      end

  end
  
  def update
    if current_user[:type] == "Delegate" or current_user.admin == true
      @directive = PersonalDirective.find_by(id: params[:id])
      @directive.update_attributes(directive_params)
      redirect_to personal_directives_path
    else
      flash[:error] = "Not editable"
      redirect_to request.referrer
    end
  end
  
  def edit
    @directive = PersonalDirective.find_by(id: params[:id])
  end

  def index

    committee_users = "SELECT users.id FROM users WHERE users.committee = :committee"
    relevant_directives = "SELECT directive_id FROM directives_users WHERE user_id in (#{committee_users})"
    relevant_tags = "SELECT tag_id FROM directives_tags WHERE directive_id in (#{relevant_directives})"
    tags = Tag.where("tags.id in (#{relevant_tags})",committee: current_user.committee)
    if user_signed_in?
      @filterrific = initialize_filterrific(
          PersonalDirective,
          params[:filterrific],
          select_options: {
              with_tag_name: tags.options_for_select,
              with_user: Delegate.where(committee: current_user.committee).options_for_select,
          }
      ) or return
      filter_result = @filterrific.find

      comments = PersonalDirective.with_comments



      if current_user[:type] == "Delegate"
        personal_directive_ids = "SELECT directive_id FROM directives_users
                          WHERE user_id = :user_id AND type = 'IssueDirective'"
        sql_result = PersonalDirective.with_committees(current_user.committee).where("directives.id IN (#{personal_directive_ids})",
                                             user_id: current_user[:id])

        @directive = current_user.directives.build(type: "PersonalDirective")

      elsif current_user[:type] == "Crisis"
        user_ids = "SELECT users.id FROM users WHERE committee = :committee"
        personal_directive_ids = "SELECT directive_id FROM directives_users
                          WHERE user_id IN (#{user_ids}) AND type = 'IssueDirective'"
        sql_result = PersonalDirective.with_committees(current_user.committee).where("directives.id IN (#{personal_directive_ids})",
                                             committee: current_user[:committee])

      end

      @pd_feed = sql_result & filter_result
      if params[:reply]
        @pd_feed = (@pd_feed - comments).paginate(page: params[:pd_page], per_page: 10)
      else
        @pd_feed = @pd_feed.paginate(page: params[:pd_page], per_page: 10)
      end


    else redirect_to root_url
    end
  end

  private
    def directive_params
      params.require(:personal_directive).permit(:content, :picture, :title, :type, :status, :editable, :quality, :claim)
    end
end

app/views/personal_directives/_pd_feed.html.erb
<% if @pd_feed.any? %>

  <ol class="directives">
    <%= render partial: "personal_directives/personal_directives", collection: @pd_feed, as: 'directive' %>
  </ol>
  
  <%= will_paginate @pd_feed, :param_name => 'pd_page' %>
<% end %>

app/views/personal_directives/_personal_directives.html.erb
<li id="directive-<%= directive.id %>">
  <span class="content">
    <b>Authors: </b>
    <% directive.users.each do |user| %>
    <%= user.position %>,
    <% end %>
  </span>
  <span class="content" >
  <% if current_user.type == "Crisis" %>
    <% if !directive.claim %>
    <b>Unclaimed(<%= link_to "claim", directive_path(directive, :directive => {:claim => true}),
                          :method => :put,
                          :confirm => "Are you sure?" %>):</b>
    <% else %>
    <b>Claimed</b>
    <% end %>
  </span>
    <span class="content">
      <% if !directive.quality.nil? %>
        <b>Quality Rating: </b>
          <%= directive.quality %>
      <% else %>
        <%= render 'personal_directives/score', :directive_id => directive.id %>
      <% end %>
    </span>
  <% end %>
  <span class= "content">
    <b>Posted: </b>
    <%= I18n.l directive.created_at.in_time_zone('Eastern Time (US & Canada)') , :format => :short  %>
  </span>
  <% if current_user[:type] == "Crisis" %>
    <span class = "content">
      <b>Tags: </b>
      <% directive.tags.each do |tag| %>
            #<%= tag.tag %>
      <% end %>
      <%= link_to "new tags",
                  :controller => "tags",
                  :action => "new",
                  :directive_id => directive.id %>
    </span>
  <% end %>
  <span class= "content">
    <b>Title: </b>
    <%= directive.title %>
  </span>
  <span class= "content">
    <b>Content: </b><br>
    <%= render inline: directive.content %>
    <%= image_tag directive.picture.url if directive.picture? %>
  </span>
  <span class= "content">
    <% if (directive.users.include?(current_user) && directive[:editable] == true &&
       !directive.comments.any?) or current_user.admin == true %>
      <b>Avaliable Actions: </b>
      <%= link_to "delete", directive, method: :delete,
                                       data: { confirm: "You sure?" } %>
      <%= link_to "edit", 
                        :controller => "directives",
                        :action => "edit",
                        :id => directive.id %>
    <% end %>


  </span>
  <span class="content">
    <br>
    <b>Replies </b><% if !directive.comments.any? %>
        (<%= link_to "new reply",
                {:controller => "comments",
                :action => "new",
                :function => "Crisis Replies",
                :directive_id => directive.id},
                :target => "_blank"
                 %>)
        <% end %>:
    <%= comments_tree_for directive.comments.hash_tree %>
  </span>
</li>
<hr style="height: 5px; border: 0px solid black; border-top-width: 1px;" />

app/views/personal_directives/_score.html.erb
<% directive = PersonalDirective.find_by(id: directive_id) %>
<b>Rate Quality:</b>
<%= link_to "1", directive_path(directive, :directive => {:quality => 1}),
            :method => :put %>,
<%= link_to "2", directive_path(directive, :directive => {:quality => 2}),
             :method => :put %>,
<%= link_to "3", directive_path(directive, :directive => {:quality => 3}),
             :method => :put %>,
<%= link_to "4", directive_path(directive, :directive => {:quality => 4}),
             :method => :put %>,
<%= link_to "5", directive_path(directive, :directive => {:quality => 5}),
             :method => :put %>

app/views/personal_directives/index.erb
<% if user_signed_in? %>
    <% provide(:title, current_user.position) %>
    <% @user = current_user %>
    <div class="row">
      <aside class="col-md-3">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <% if current_user.type == "Crisis" %>
        <%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
            <div>
              Search
              <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
              <%= f.text_field(
                      :search_query,
                  ) %>
            </div>
            <div>
              Tags
              <%= f.select(
                      :with_tag_name,
                      @filterrific.select_options[:with_tag_name],
                      { include_hidden: false, include_blank: '- Any -' },
                      multiple:true,
                      class: "chosen-select form-control"
                  ) %>
            </div>
            <div>
              User
              <%= f.select(
                      :with_user,
                      @filterrific.select_options[:with_user],
                      { include_hidden: false, include_blank: '- Any -' },
                      multiple:true,
                      class: "chosen-select form-control"
                  ) %>
            </div>
            <div>
              Unreplied Directives?
              <%= check_box_tag('reply', value: "false", checked: false) %>
            </div>

            <%= f.submit "submit" %>


        <% end %>
        <% end %>
        <% if current_user.type == "Delegate" %>
            <%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
                <div>
                  Search
                  <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
                  <%= f.text_field(
                          :search_query,
                      ) %>
                </div>
                <%= f.submit "submit" %>
            <% end %>
        <% end %>
      </aside>

      <div class="col-md-9">

          <h3>Personal Directives (Crisis Notes) (<%= @pd_feed.count %>)</h3>
          <%= link_to "new personal directives", new_personal_directive_path, :target => '_blank' if current_user[:type] == "Delegate"%>
          <ol class="directives">
            <%= render "pd_feed" %>
          </ol>
      </div>
    </div>
<% end %>


app/views/personal_directives/index.js.erb
<% js = escape_javascript(
        render('shared/pd_feed')) %>
$("#filterrific_results").html("<%= js %>");

app/views/personal_directives/new.html.erb
<h2>New Personal Directives (Crisis Notes)</h2>

<%= form_for(@personal_directives) do |f| %>
    <% if @personal_directives.errors.any? %>
        <div id="error_explanation">
          <h5><%= pluralize(@personal_directives.errors.count, "error") %> prohibited this directive from being saved:</h5>

          <ul>
            <% @personal_directives.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <b>Co-Authors</b>
      <%= select_tag(:other_authors, options_for_select(Delegate.where(committee: current_user.committee).where.not(id: current_user.id).collect {|p| [ p.position, p.id ] }), { multiple: true , class: "chosen-select form-control" })%>
    </div>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :content %>
      <%= f.text_area :content, :class => "tinymce" %>
      <%= tinymce %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>

<% end %>